### ISSUE TITLE
「音声認識開始」のブロックが走るときに「音声」の中身をクリアしたほうが良さそう

### ISSUE THREAD

**Issue by champierre** [champierre/speech2scratch#1]
「音声認識開始」のブロックが走るときに「音声」の中身をクリアしたほうが良さそうな気がしました。
もしくは、「音声をクリアする」的なブロックを用意するか。
理由は、音声認識がうまくできなかったときにも前回の値（「音声」）が結果として返されているような動作に見えるためです。

**Comment by kwaka1208** [comment]
同じく、「音声認識開始」のブロックが走るときに「音声」の中身が初期化されるといいなと思いました。明示的にクリアするブロックが別途あってもいいと思いますが、それとは別に認識開始時に自動的にクリアされた方が使いやすいと思います。

**Comment by champierre** [comment]
https://github.com/champierre/speech2scratch/pull/5 で解決しました。
